version = 1

test_patterns = ["**/__tests__/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  dialect = "typescript"
  environment = ["nodejs", "jest"]
  module_system = "es-modules"
  dependency_file_paths = [
    "client/package.json",
    "package.json"
  ]

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
